// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64
	Username string
	Email    string
	PassHash string
	OnBoard  pgtype.Bool
	UserType string
}
